Repository MeeTeamIdle/MeeTeam_FrontEnd, pull requests merged in 2024-04, with the labels that each got.

#102 refactor: ProfileImage 공통 컴포넌트 적용
  package-lock.json
  package.json
  src/assets/index.ts
  src/components/comment/comment/Comment.tsx
  src/components/comment/comment/ReplyComment.tsx
  src/components/comment/commentInput/CommentInput.tsx
  src/components/comment/replyInput/ReplyInput.tsx
  src/components/dateSelect/DateSelect.tsx
  src/components/dateSelect/DeadlineSelect.tsx
  src/components/header/Header.tsx
  src/components/inputDropdown/inputRole/InputRoleForm.tsx
  src/components/meeteam/card/RecruitCard.tsx
  src/components/profile/image/ProfileImage.tsx
  src/components/recruit/applicants/ApplicantCard.tsx
  src/components/recruit/recruitDetail/titleInfo/TitleInfo.tsx
  src/service/index.ts
  src/types/index.ts
  src/types/indexSigniture.ts
  src/types/recruit/response.ts
Labels: Priority: Critical, Status: Review Needed, Type: Refactor

#103 feat: 포트폴리오 상세 페이지 UI 및 기능 및 API 연동 구현
  package-lock.json
  package.json
  src/assets/ArrowLeft.svg
  src/assets/ArrowRight.svg
  src/assets/LinkIcon.svg
  src/assets/Test1.png
  src/assets/Test2.png
  src/assets/Test3.png
  src/assets/Test4.png
  src/assets/index.ts
  src/components/carousel/ImageCarousel.styled.ts
  src/components/carousel/ImageCarousel.tsx
  src/components/carousel/imageList.ts
  src/components/index.ts
  src/components/link/details/LinkDetails.styled.ts
  src/components/link/details/LinkDetails.tsx
  src/components/portfolio/information/PortfolioInformation.styled.ts
  src/components/portfolio/information/PortfolioInformation.tsx
  src/components/portfolio/list/PortfolioList.styled.ts
  src/components/portfolio/list/PortfolioList.tsx
  src/hooks/index.ts
  src/hooks/usePortfolio.ts
  src/main.tsx
  src/pages/index.ts
  src/pages/portfolio/details/PortfolioDetails.styled.ts
  src/pages/portfolio/details/PortfolioDetailsPage.tsx
  src/pages/portfolio/portfolioData.ts
  src/service/endPoint.ts
  src/service/index.ts
  src/service/portfolio/portfolio.ts
  src/types/image.ts
  src/types/index.ts
  src/types/portfolio.ts
  src/types/user.ts
Labels: Priority: Critical, Status: Review Needed, Type: Feature, Type: Style

#117 chore: 신청자 관리 일부 버그 수정
  src/assets/LinkIcon.svg
  src/pages/recruit/applierManagePage/ApplierManagePage.styled.ts
  src/pages/recruit/applierManagePage/ApplierManagePage.tsx
Labels: Type: Bug
