Repository MeeTeamIdle/MeeTeam_FrontEnd, pull requests merged in 2024-07, with the labels that each got.

#231 feat: Refresh token & Access token 적용하여 로그인 동작 변경
  src/components/recruit/recruitDetail/modal/accountDelete/AccountDelete.tsx
  src/env.d.ts
  src/hooks/useAuth.ts
  src/service/auth/auth.ts
  src/service/axiosInstance.ts
  src/service/endPoint.ts
  src/service/index.ts
Labels: Priority: Critical, Status: Review Needed, Type: Improvement

#235 feat: 이미지 업로드 위한 presignedURL -> signedURL 발급 엔드포인트 변경
  src/service/endPoint.ts
Labels: Priority: Critical, Status: Review Needed, Type: Feature

#237 fix: 1차 UT 피드백_개선사항_버그_수정
  src/assets/index.ts
  src/assets/meeteam_banner_icon.png
  src/components/header/Header.tsx
  src/components/recruit/create/ControlButtons.tsx
  src/components/recruit/create/basicInformation/BasicInformation.styled.ts
  src/components/recruit/create/basicInformation/BasicInformation.tsx
  src/components/recruit/create/basicInformation/containers/ContainerCourse.tsx
  src/components/recruit/create/basicInformation/containers/ContainerProcedure.tsx
  src/components/recruit/create/detailedInformation/DetailedInformation.tsx
  src/components/recruit/recruitDetail/modal/ApplyModal.styled.ts
  src/components/recruit/recruitDetail/modal/ApplyModal.tsx
  src/components/recruit/recruitDetail/modal/ConfirmModal.tsx
  src/components/recruit/recruitDetail/modal/FinalModal.tsx
  src/constant/index.ts
  src/constant/initFormData.ts
  src/pages/create/recruitCreatePage/RecruitCreatePage.tsx
  src/pages/recruit/recruitDetailPage/RecruitDetailPage.tsx
  src/pages/recruit/recruitPage/RecruitPage.styled.ts
  src/pages/recruit/recruitPage/RecruitPage.tsx
  src/utils/index.ts
  src/utils/resetFormData.ts
Labels: Priority: Critical, Status: Review Needed, Type: Bug, Type: Refactor
