Repository MeeTeamIdle/MeeTeam_FrontEnd, pull requests merged in 2024-11, with the labels that each got.

#268 feat: #267 구글 애널리틱스 userId 적용
  index.html
Labels: Priority: Medium, Status: Review Needed, Type: Feature, D-1

#272 fix: 닉네임 중복 체크 시, 불필요한 api 호출 이슈 해결
  src/hooks/useAuth.ts
  src/pages/account/nicknameSetting/NicknameSettingPage.tsx
Labels: Priority: Medium, Status: Review Needed, Type: Bug, D-1

#274 fix: 프로필 편집 시 엔터 키 누르면 편집 폼 제출되는 이슈 해결
  src/pages/portfolio/edit/PortfolioEditPage.tsx
  src/pages/profile/edit/ProfileEditPage.tsx
  src/utils/checkEnterKeyDown.ts
  src/utils/index.ts
Labels: Priority: Critical, Status: Review Needed, Type: Bug, D-1

#282 refactor: 입력창 UX 개선 및 교내/교외 분리 요청사항 반영
  src/components/dropdown/Dropdown.tsx
  src/components/dropdown/dropdownDetail/DropdownDetail.styled.ts
  src/components/dropdown/textBox/TextBox.tsx
  src/components/header/Header.tsx
  src/components/index.ts
  src/components/inputDropdown/inputRole/InputRoleForm.tsx
  src/components/meeteam/card/RecruitCard.tsx
  src/components/recruit/create/ControlButtons.tsx
  src/components/recruit/create/basicInformation/BasicInformation.styled.ts
  src/components/recruit/create/basicInformation/containers/ContainerCourse.tsx
  src/components/recruit/recruitBoard/detailedFilter/DetailedInput.tsx
  src/components/tag/MeeteamTag.tsx
  src/hooks/index.ts
  src/hooks/useCheckDevice.ts
  src/main.tsx
  src/pages/account/signIn/SignInPage.tsx
  src/pages/recruit/recruitCreatePage/RecruitCreatePage.styled.ts
  src/pages/recruit/recruitCreatePage/RecruitCreatePage.tsx
  src/pages/recruit/recruitPage/RecruitPage.tsx
  src/pages/routes/PrivateRouter.tsx
Labels: Priority: High, Status: Review Needed, Type: Bug, Type: Improvement, D-1

#266 refactor: 교내 / 교외 탭 분리, Suspense, lazy loading 적용
  index.html
  public/meeteam_banner_icon_large.webp
  public/meeteam_banner_icon_medium.webp
  public/meeteam_banner_icon_small.webp
  public/meeteam_banner_icon_xlarge.png
  src/atom.tsx
  src/components/dropdown/Dropdown.styled.ts
  src/components/dropdown/Dropdown.tsx
  src/components/dropdown/dropdownDetail/DropdownDetail.styled.ts
  src/components/dropdown/textBox/TextBox.tsx
  src/components/header/Header.tsx
  src/components/index.ts
  src/components/inputDropdown/inputRole/InputRoleForm.tsx
  src/components/loading/LoadingBackground.styled.ts
  src/components/loading/LoadingBackground.tsx
  src/components/meeteam/card/RecruitCard.tsx
  src/components/progressBar/Progress.styled.ts
  src/components/progressBar/Progress.tsx
  src/components/recruit/create/ControlButtons.tsx
  src/components/recruit/create/basicInformation/BasicInformation.styled.ts
  src/components/recruit/create/basicInformation/containers/ContainerCourse.tsx
  src/components/recruit/recruitBoard/banner/MainBanner.tsx
  src/components/recruit/recruitBoard/detailedFilter/DetailedInput.tsx
  src/components/tag/MeeteamTag.tsx
  src/constant/loginModalMessage.ts
  src/hooks/index.ts
  src/hooks/useCheckDevice.ts
  src/main.tsx
  src/pages/GalaryPage.tsx
  src/pages/account/accountSetting/AccountSetting.styled.ts
  src/pages/account/accountSetting/AccountSetting.tsx
  src/pages/account/signIn/SignInPage.tsx
  src/pages/index.ts
  src/pages/recruit/recruitCreatePage/RecruitCreatePage.styled.ts
  src/pages/recruit/recruitCreatePage/RecruitCreatePage.tsx
  src/pages/recruit/recruitDetailPage/RecruitDetailPage.tsx
  src/pages/recruit/recruitPage/RecruitPage.tsx
  src/pages/routes/PrivateRouter.tsx
  src/service/recruit/board.ts
  src/service/recruit/detail.ts
Labels: Priority: Critical, Status: Review Needed, Type: Improvement, Type: Refactor, D-0

#285 feat: 로그인/회원가입, 프로필, 포트폴리오 관련 페이지 반응형 웹 기능 구현
  src/components/link/details/LinkDetails.styled.ts
  src/components/link/details/LinkDetails.tsx
  src/components/portfolio/image/upload/PortfolioImageUpload.styled.ts
  src/components/portfolio/information/PortfolioInformation.styled.ts
  src/components/portfolio/information/PortfolioInformation.tsx
  src/components/profile/image/ProfileImage.styled.ts
  src/constant/deviceSize.ts
  src/constant/index.ts
  src/hooks/useCheckDevice.ts
  src/pages/account/Account.styled.ts
  src/pages/account/schoolCertification/SchoolCertificationPage.styled.ts
  src/pages/account/schoolCertification/SchoolCertificationPage.tsx
  src/pages/portfolio/details/PortfolioDetails.styled.ts
  src/pages/portfolio/details/PortfolioDetailsPage.tsx
  src/pages/portfolio/edit/PortfolioEdit.styled.ts
  src/pages/portfolio/edit/PortfolioEditPage.tsx
  src/pages/profile/Profile.styled.ts
  src/pages/profile/details/ProfileDetailsPage.tsx
  src/pages/profile/edit/ProfileEditPage.tsx
  src/types/common.ts
  src/types/index.ts
Labels: Priority: Critical, Status: Review Needed, Type: Feature, Type: Style, D-1

#288 feat: 반응형에 따른 PortfolioImageModal 컴포넌트 스타일링 변경
  src/components/portfolio/image/modal/PortfolioImageModal.styled.ts
  src/components/portfolio/image/modal/PortfolioImageModal.tsx
Labels: Priority: Critical, Status: Available, Type: Feature

#294 feat: release-tag 자동화 설정
  .github/workflows/deployment.yml
  .github/workflows/release_tag.yml
Labels: Priority: Medium, Status: Review Needed, D-3
