Repository MeeTeamIdle/MeeTeam_FrontEnd, pull requests merged in 2024-06, with the labels that each got.

#211 fix: 디자인팀 QA - (긴급) 신청 모달 수정사항 반영
  src/atom.tsx
  src/components/recruit/recruitDetail/modal/ApplyModal.styled.ts
  src/components/recruit/recruitDetail/modal/ApplyModal.tsx
  src/components/recruit/recruitDetail/modal/ConfirmModal.tsx
  src/components/recruit/recruitDetail/modal/FinalModal.tsx
  src/globalStyle.css
  src/pages/recruit/recruitDetailPage/RecruitDetailPage.tsx
  src/pages/recruit/recruitPage/RecruitPage.styled.ts
Labels: Priority: Critical, Status: Review Needed, Type: Improvement

#214 fix: 오픈채팅방 모달 버그 및 회원가입 이후 로그인 필요 버그 작업
  src/components/header/Header.tsx
  src/components/recruit/applicants/modal/OpenChatModal.tsx
  src/service/recruit/applicant.ts
Labels: Priority: Critical, Type: Bug

#208 refactor: 역할 입력폼 기능 개선 및 디자인 수정, 일부 버그 수정
  src/assets/NotFoundIcon.png
  src/assets/index.ts
  src/atom.tsx
  src/components/inputDropdown/inputRole/InputRoleForm.styled.ts
  src/components/inputDropdown/inputRole/InputRoleForm.tsx
  src/components/recruit/create/recruitRoles/RecruitRolesForm.styled.ts
  src/components/recruit/create/recruitRoles/RecruitRolesForm.tsx
  src/components/recruit/recruitDetail/modal/needLogin/NeedLogin.styled.ts
  src/globalStyle.css
  src/hooks/useValid.ts
  src/pages/create/recruitCreatePage/RecruitCreatePage.styled.ts
  src/pages/create/recruitCreatePage/RecruitCreatePage.tsx
  src/pages/notFound/NotFound.tsx
  src/utils/resetFormData.ts
Labels: Priority: High, Status: Review Needed, Type: Bug, Type: Feature, Type: Improvement, Type: Refactor, Type: Style

#224 deploy: 회원탈퇴 기능 추가 - 배포 사이트에 적용
  src/App.tsx
  src/atom.tsx
  src/components/index.ts
  src/components/recruit/recruitDetail/modal/accountDelete/AccountDelete.tsx
  src/components/recruit/recruitDetail/modal/applyClose/ApplyClose.styled.ts
  src/globalStyle.css
  src/hooks/useLogin.ts
  src/pages/account/accountSetting/AccountSetting.styled.ts
  src/pages/account/accountSetting/AccountSetting.tsx
  src/pages/routes/PrivateRouter.tsx
  src/service/auth/auth.ts
  src/service/endPoint.ts
  src/service/index.ts
Labels: Status: Available

#225 fix: 프로필 편집 페이지 UT 2차 이슈 해결
  global.d.ts
  src/assets/Congratulation.png
  src/assets/index.ts
  src/components/carousel/ImageCarousel.tsx
  src/pages/account/complete/CompleteSignUpPage.tsx
  src/pages/portfolio/edit/PortfolioEditPage.tsx
  src/pages/profile/details/ProfileDetailsPage.tsx
  src/pages/profile/edit/ProfileEditPage.tsx
Labels: Priority: Critical, Status: Review Needed, Type: Bug

#226 fix: 프로필 편집 페이지 UT 2차 이슈 해결 배포 브랜치에 적용
  global.d.ts
  src/assets/Congratulation.png
  src/assets/index.ts
  src/components/carousel/ImageCarousel.tsx
  src/pages/account/complete/CompleteSignUpPage.tsx
  src/pages/portfolio/edit/PortfolioEditPage.tsx
  src/pages/profile/details/ProfileDetailsPage.tsx
  src/pages/profile/edit/ProfileEditPage.tsx
Labels: Priority: Critical, Type: Bug

#227 feat: 임시 반응형 UI 적용(모바일 한정)
  src/components/dropdown/Dropdown.styled.ts
  src/components/dropdown/Dropdown.tsx
  src/components/footer/Footer.styled.ts
  src/components/footer/Footer.tsx
  src/components/header/Header.styled.ts
  src/components/inputDropdown/inputRole/InputRoleForm.styled.ts
  src/components/meeteam/card/Card.styled.ts
  src/components/muiDatepicker/MuiDatepicker.tsx
  src/components/recruit/applicants/modal/OpenChatModal.styled.ts
  src/components/recruit/applicants/toast/Toast.styled.ts
  src/components/recruit/applicants/toast/Toast.tsx
  src/components/recruit/create/basicInformation/BasicInformation.styled.ts
  src/components/recruit/create/basicInformation/BasicInformation.tsx
  src/components/recruit/create/basicInformation/containers/ContainerCourse.tsx
  src/components/recruit/create/detailedInformation/DetailedInformation.styled.ts
  src/components/recruit/create/recruitRoles/RecruitRolesForm.styled.ts
  src/components/recruit/recruitBoard/detailedFilter/DetailedInput.tsx
  src/components/recruit/recruitDetail/modal/ApplyModal.styled.ts
  src/components/recruit/recruitDetail/modal/ApplyModal.tsx
  src/components/recruit/recruitDetail/modal/ConfirmModal.tsx
  src/components/recruit/recruitDetail/modal/applyCancel/ApplyCancel.styled.ts
  src/components/recruit/recruitDetail/modal/applyCancel/ApplyCancel.tsx
  src/components/recruit/recruitDetail/modal/applyClose/ApplyClose.styled.ts
  src/components/recruit/recruitDetail/modal/needLogin/NeedLogin.styled.ts
  src/components/recruit/recruitDetail/recruitDescription/RecruitDescription.styled.ts
  src/components/recruit/recruitDetail/recruitInfo/RecruitInfo.styled.ts
  src/components/recruit/recruitDetail/recruitInfo/RecruitInfo.tsx
  src/components/recruit/recruitDetail/titleInfo/TitleInfo.styled.ts
  src/components/recruit/recruitDetail/titleInfo/TitleInfo.tsx
  src/pages/account/accountSetting/AccountSetting.styled.ts
  src/pages/account/accountSetting/AccountSetting.tsx
  src/pages/create/recruitCreatePage/RecruitCreatePage.styled.ts
  src/pages/recruit/applierManagePage/ApplierManagePage.styled.ts
  src/pages/recruit/applierManagePage/ApplierManagePage.tsx
  src/pages/recruit/recruitDetailPage/RecruitDetailPage.styled.ts
  src/pages/recruit/recruitManagePage/RecruitManagePage.styled.ts
  src/pages/recruit/recruitManagePage/RecruitManageWrapper.tsx
  src/pages/recruit/recruitPage/RecruitPage.styled.ts
Labels: Priority: Critical, Status: Review Needed, Type: Feature, Type: Improvement
