Repository MeeTeamIdle/MeeTeam_FrontEnd, pull requests merged in 2024-05, with the labels that each got.

#120 feat: 포트폴리오 관리 페이지 UI 및 기능 및 API 연동 구현
  src/components/index.ts
  src/components/pagination/Pagination.styled.ts
  src/components/tabMenu/TabMenu.styled.ts
  src/components/tabMenu/TabMenu.tsx
  src/hooks/index.ts
  src/hooks/usePortfolio.ts
  src/main.tsx
  src/pages/index.ts
  src/pages/portfolio/management/PortfolioManagementPage.styled.ts
  src/pages/portfolio/management/PortfolioManagmentPage.tsx
  src/pages/profile/edit/ProfileEditPage.tsx
  src/service/endPoint.ts
  src/service/index.ts
  src/service/portfolio/portfolio.ts
  src/types/response.ts
Labels: Priority: Critical, Status: Review Needed, Type: Feature, Type: Style

#127 fix: 남의 프로필 이미지가 본인 이미지로 보이는 이슈 수정
  src/components/header/Header.tsx
  src/components/profile/image/ProfileImage.tsx
  src/pages/profile/edit/ProfileEditPage.tsx
Labels: Priority: Critical, Status: Review Needed, Type: Bug

#128 fix: 남의 프로필 이미지가 본인 이미지로 보이는 이슈 수정
  src/components/header/Header.tsx
  src/components/profile/image/ProfileImage.tsx
  src/pages/profile/edit/ProfileEditPage.tsx
Labels: Priority: Critical, Type: Bug

#122 fix: 1차 QA 수정사항
  package-lock.json
  src/atom.tsx
  src/components/comment/comment/Comment.tsx
  src/components/comment/comment/ReplyComment.tsx
  src/components/dropdown/Dropdown.styled.ts
  src/components/dropdown/Dropdown.tsx
  src/components/index.ts
  src/components/inputDropdown/inputRole/InputRoleForm.styled.ts
  src/components/inputDropdown/inputRole/InputRoleForm.tsx
  src/components/pagination/Pagination.tsx
  src/components/recruit/applicants/ApplicantCard.styled.ts
  src/components/recruit/applicants/ApplicantCard.tsx
  src/components/recruit/applicants/modal/ApproveModal.tsx
  src/components/recruit/applicants/modal/Modal.styled.ts
  src/components/recruit/applicants/modal/RefuseModal.tsx
  src/components/recruit/create/ControlButtons.tsx
  src/components/recruit/create/basicInformation/BasicInformation.styled.ts
  src/components/recruit/create/basicInformation/containers/ContainerCourse.tsx
  src/components/recruit/recruitBoard/detailedFilter/DetailedInput.tsx
  src/components/recruit/recruitDetail/footer/ApplierFooter.tsx
  src/components/recruit/recruitDetail/footer/WriterFooter.tsx
  src/components/recruit/recruitDetail/linktoList/LinkToList.tsx
  src/components/recruit/recruitDetail/modal/ApplyModal.styled.ts
  src/components/recruit/recruitDetail/modal/ApplyModal.tsx
  src/components/recruit/recruitDetail/modal/applyCancel/ApplyCancel.styled.ts
  src/components/recruit/recruitDetail/modal/applyCancel/ApplyCancel.tsx
  src/components/recruit/recruitDetail/recruitDescription/RecruitDescription.styled.ts
  src/components/recruit/recruitDetail/recruitRoles/RecruitRoles.styled.ts
  src/components/recruit/recruitDetail/titleInfo/TitleInfo.styled.ts
  src/constant/loginModalMessage.ts
  src/globalStyle.css
  src/hooks/useValid.ts
  src/main.tsx
  src/pages/create/recruitCreatePage/RecruitCreatePage.tsx
  src/pages/index.ts
  src/pages/recruit/applierManagePage/ApplierManagePage.styled.ts
  src/pages/recruit/applierManagePage/ApplierManagePage.tsx
  src/pages/recruit/recruitDetailPage/RecruitDetailPage.styled.ts
  src/pages/recruit/recruitDetailPage/RecruitDetailPage.tsx
  src/pages/recruit/recruitManagePage/RecruitManagePage.styled.ts
  src/pages/recruit/recruitManagePage/RecruitMyPostings.tsx
  src/pages/recruit/recruitManagePage/RecruitPostingApply.tsx
  src/pages/recruit/recruitManagePage/RecruitPostingBookmark.tsx
  src/pages/recruit/recruitPage/RecruitPage.styled.ts
  src/pages/recruit/recruitPage/RecruitPage.tsx
  src/pages/routes/PrivateRouter.tsx
  src/service/axiosInstance.ts
  src/service/recruit/board.ts
  src/types/recruit/payload.ts
  src/types/recruit/response.ts
  src/utils/editorModule.ts
Labels: Priority: Critical, Type: Bug, Type: Improvement

#136 fix: 2차 QA 수정사항 작업
  src/atom.tsx
  src/components/comment/comment/Comment.tsx
  src/components/comment/comment/ReplyComment.tsx
  src/components/comment/commentInput/CommentInput.styled.ts
  src/components/comment/commentInput/CommentInput.tsx
  src/components/comment/replyInput/ReplyInput.styled.ts
  src/components/comment/replyInput/ReplyInput.tsx
  src/components/dateSelect/DateSelect.tsx
  src/components/dropdown/Dropdown.styled.ts
  src/components/dropdown/Dropdown.tsx
  src/components/header/Header.tsx
  src/components/index.ts
  src/components/meeteam/card/RecruitCard.tsx
  src/components/recruit/applicants/modal/RefuseModal.tsx
  src/components/recruit/applicants/toast/Toast.styled.ts
  src/components/recruit/create/detailedInformation/DetailedInformation.tsx
  src/components/recruit/recruitBoard/detailedFilter/DetailedInput.tsx
  src/components/recruit/recruitDetail/footer/ApplierFooter.tsx
  src/components/recruit/recruitDetail/footer/WriterFooter.tsx
  src/components/recruit/recruitDetail/modal/applyCancel/ApplyCancel.tsx
  src/components/recruit/recruitDetail/modal/applyClose/ApplyClose.tsx
  src/components/recruit/recruitDetail/modal/commentDelete/CommentDeleteModal.tsx
  src/components/recruit/recruitDetail/modal/postingDelete/PostingDelete.tsx
  src/components/recruit/recruitDetail/recruitInfo/RecruitInfo.tsx
  src/components/recruit/recruitDetail/recruitRoles/RecruitRoles.styled.ts
  src/components/recruit/recruitDetail/recruitRoles/RecruitRoles.tsx
  src/components/recruit/role/RoleCard.styled.ts
  src/components/tag/MeeteamTag.tsx
  src/constant/index.ts
  src/constant/textEditor.ts
  src/hooks/useValid.ts
  src/pages/create/recruitCreatePage/RecruitCreatePage.tsx
  src/pages/recruit/applierManagePage/ApplierManagePage.styled.ts
  src/pages/recruit/applierManagePage/ApplierManagePage.tsx
  src/pages/recruit/recruitDetailPage/RecruitDetailPage.styled.ts
  src/pages/recruit/recruitDetailPage/RecruitDetailPage.tsx
  src/pages/recruit/recruitPage/RecruitPage.styled.ts
  src/pages/recruit/recruitPage/RecruitPage.tsx
  src/types/recruit/payload.ts
  src/utils/index.ts
  src/utils/resetFormData.ts
  src/utils/throttle.ts
Labels: Priority: Critical, Type: Bug

#137 fix: 2차 QA 수정사항 작업
  src/atom.tsx
  src/components/comment/comment/Comment.tsx
  src/components/comment/comment/ReplyComment.tsx
  src/components/comment/commentInput/CommentInput.styled.ts
  src/components/comment/commentInput/CommentInput.tsx
  src/components/comment/replyInput/ReplyInput.styled.ts
  src/components/comment/replyInput/ReplyInput.tsx
  src/components/dateSelect/DateSelect.tsx
  src/components/dropdown/Dropdown.styled.ts
  src/components/dropdown/Dropdown.tsx
  src/components/header/Header.tsx
  src/components/index.ts
  src/components/meeteam/card/RecruitCard.tsx
  src/components/recruit/applicants/modal/RefuseModal.tsx
  src/components/recruit/applicants/toast/Toast.styled.ts
  src/components/recruit/create/detailedInformation/DetailedInformation.tsx
  src/components/recruit/recruitBoard/detailedFilter/DetailedInput.tsx
  src/components/recruit/recruitDetail/footer/ApplierFooter.tsx
  src/components/recruit/recruitDetail/footer/WriterFooter.tsx
  src/components/recruit/recruitDetail/modal/applyCancel/ApplyCancel.tsx
  src/components/recruit/recruitDetail/modal/applyClose/ApplyClose.tsx
  src/components/recruit/recruitDetail/modal/commentDelete/CommentDeleteModal.tsx
  src/components/recruit/recruitDetail/modal/postingDelete/PostingDelete.tsx
  src/components/recruit/recruitDetail/recruitInfo/RecruitInfo.tsx
  src/components/recruit/recruitDetail/recruitRoles/RecruitRoles.styled.ts
  src/components/recruit/recruitDetail/recruitRoles/RecruitRoles.tsx
  src/components/recruit/role/RoleCard.styled.ts
  src/components/tag/MeeteamTag.tsx
  src/constant/index.ts
  src/constant/textEditor.ts
  src/hooks/useValid.ts
  src/pages/create/recruitCreatePage/RecruitCreatePage.tsx
  src/pages/recruit/applierManagePage/ApplierManagePage.styled.ts
  src/pages/recruit/applierManagePage/ApplierManagePage.tsx
  src/pages/recruit/recruitDetailPage/RecruitDetailPage.styled.ts
  src/pages/recruit/recruitDetailPage/RecruitDetailPage.tsx
  src/pages/recruit/recruitPage/RecruitPage.styled.ts
  src/pages/recruit/recruitPage/RecruitPage.tsx
  src/types/recruit/payload.ts
  src/utils/index.ts
  src/utils/resetFormData.ts
  src/utils/throttle.ts
Labels: Priority: Critical, Type: Bug, Type: Improvement

#138 chore: 상세조건 하이라이트 버그 수정
  src/components/recruit/recruitBoard/detailedFilter/DetailedInput.tsx
  src/pages/recruit/recruitPage/RecruitPage.tsx
  src/types/recruit/payload.ts
Labels: Priority: Critical, Type: Bug

#139 chore: 분야 조건 동작 변경
  src/pages/recruit/recruitPage/RecruitPage.tsx
Labels: Priority: Critical

#141 fix: 프로필 상세 페이지 1차 QA 피드백 적용
  src/assets/Clip.svg
  src/assets/index.ts
  src/components/link/details/LinkDetails.tsx
  src/pages/profile/Profile.styled.ts
  src/pages/profile/details/ProfileDetailsPage.tsx
Labels: Priority: Critical, Status: Review Needed, Type: Feature, Type: Style

#143 fix: 포트폴리오 관리 페이지 1차 QA 피드백 적용
  src/pages/portfolio/management/PortfolioManagementPage.styled.ts
  src/pages/portfolio/management/PortfolioManagmentPage.tsx
Labels: Priority: Critical, Status: Review Needed, Type: Bug

#145 feat: 포트폴리오 관리 페이지 1차 QA 피드백 배포 브랜치에 적용
  src/pages/portfolio/management/PortfolioManagementPage.styled.ts
  src/pages/portfolio/management/PortfolioManagmentPage.tsx
Labels: Priority: Critical, Type: Bug

#148 fix: 포트폴리오 작성/편집 페이지 1차 QA 피드백 적용
  src/components/button/AddBtn.tsx
  src/components/button/IconBtn.tsx
  src/components/comboBox/ComboBox.tsx
  src/components/index.ts
  src/components/muiDatepicker/MuiDatepicker.tsx
  src/components/muiDatepicker/MuiDatepickerController.styled.ts
  src/components/muiDatepicker/MuiDatepickerController.tsx
  src/components/radio/Radio.tsx
  src/constant/validation.ts
  src/hooks/index.ts
  src/hooks/usePortfolio.ts
  src/pages/portfolio/details/PortfolioDetails.styled.ts
  src/pages/portfolio/details/PortfolioDetailsPage.tsx
  src/pages/portfolio/edit/PortfolioEdit.styled.ts
  src/pages/portfolio/edit/PortfolioEditPage.tsx
  src/pages/portfolio/edit/portfolioEditData.ts
  src/pages/profile/edit/ProfileEditData.ts
  src/pages/profile/edit/ProfileEditPage.tsx
  src/service/endPoint.ts
  src/service/index.ts
  src/service/portfolio/portfolio.ts
Labels: Priority: Critical, Status: Review Needed, Type: Bug

#149 feat: 포트폴리오 작성/편집 페이지 1차 QA 피드백 배포 브랜치에 적용
  src/components/button/AddBtn.tsx
  src/components/button/IconBtn.tsx
  src/components/comboBox/ComboBox.tsx
  src/components/index.ts
  src/components/muiDatepicker/MuiDatepicker.tsx
  src/components/muiDatepicker/MuiDatepickerController.styled.ts
  src/components/muiDatepicker/MuiDatepickerController.tsx
  src/components/radio/Radio.tsx
  src/constant/validation.ts
  src/hooks/index.ts
  src/hooks/usePortfolio.ts
  src/pages/portfolio/details/PortfolioDetails.styled.ts
  src/pages/portfolio/details/PortfolioDetailsPage.tsx
  src/pages/portfolio/edit/PortfolioEdit.styled.ts
  src/pages/portfolio/edit/PortfolioEditPage.tsx
  src/pages/portfolio/edit/portfolioEditData.ts
  src/pages/profile/edit/ProfileEditData.ts
  src/pages/profile/edit/ProfileEditPage.tsx
  src/service/endPoint.ts
  src/service/index.ts
  src/service/portfolio/portfolio.ts
Labels: Priority: Critical, Type: Feature, Type: Style

#151 fix: 3차 QA 수정사항 작업
  package-lock.json
  package.json
  src/atom.tsx
  src/components/comment/comment/Comment.tsx
  src/components/comment/comment/ReplyComment.tsx
  src/components/comment/replyInput/ReplyInput.tsx
  src/components/meeteam/card/RecruitCard.tsx
  src/components/recruit/applicants/toast/Toast.styled.ts
  src/components/recruit/applicants/toast/Toast.tsx
  src/hooks/useAuth.ts
  src/hooks/useValid.ts
  src/pages/create/recruitCreatePage/RecruitCreatePage.tsx
  src/pages/recruit/recruitPage/RecruitPage.tsx
  vite.config.ts
Labels: Priority: Critical, Type: Bug, Type: Improvement

#152 fix: 3차 QA 수정사항 배포사이트 반영
  package-lock.json
  package.json
  src/atom.tsx
  src/components/comment/comment/Comment.tsx
  src/components/comment/comment/ReplyComment.tsx
  src/components/comment/replyInput/ReplyInput.tsx
  src/components/meeteam/card/RecruitCard.tsx
  src/components/recruit/applicants/toast/Toast.styled.ts
  src/components/recruit/applicants/toast/Toast.tsx
  src/hooks/useAuth.ts
  src/hooks/useValid.ts
  src/pages/create/recruitCreatePage/RecruitCreatePage.tsx
  src/pages/portfolio/portfolioData.ts
  src/pages/recruit/recruitPage/RecruitPage.tsx
  vite.config.ts
Labels: Priority: Critical, Type: Bug, Type: Improvement

#153 fix: 토스트 UI 로직 및 일부 코드 변경
  src/components/recruit/applicants/toast/Toast.styled.ts
Labels: Priority: Critical, Type: Bug

#154 chore: favicon 설정 - 배포 사이트 적용
  index.html
  public/MeeTeamIcon.ico
Labels: Priority: High, Type: Style

#156 fix: 포트폴리오 작성/편집 이후에도 작성 페이지에서 업로드 이미지가 보이는 이슈 해결
  src/components/portfolio/image/upload/PortfolioImageUpload.tsx
  src/pages/portfolio/portfolioData.ts
Labels: Priority: Critical, Status: Review Needed, Type: Bug

#158 fix: 프로필 편집 페이지 1차 QA 피드백 배포 브랜치에 적용
  src/components/button/Button.styled.ts
  src/components/input/Input.styled.ts
  src/components/input/Input.tsx
  src/components/portfolio/card/PortfolioCard.tsx
  src/components/portfolio/image/upload/PortfolioImageUpload.tsx
  src/constant/validation.ts
  src/pages/portfolio/portfolioData.ts
  src/pages/profile/Profile.styled.ts
  src/pages/profile/edit/ProfileEditData.ts
  src/pages/profile/edit/ProfileEditPage.tsx
Labels: Priority: Critical, Status: Available, Type: Bug

#160 fix: #159 MuiDatepickerController 유효성 검사 UI가 뜨지 않는 이슈 해결
  src/components/muiDatepicker/MuiDatepickerController.styled.ts
  src/components/muiDatepicker/MuiDatepickerController.tsx
  src/pages/profile/edit/ProfileEditPage.tsx
Labels: Priority: Critical, Status: Review Needed, Type: Bug

#161 fix: MuiDatepickerController 유효성 검사 UI가 뜨지 않는 이슈 해결
  src/components/muiDatepicker/MuiDatepickerController.styled.ts
  src/components/muiDatepicker/MuiDatepickerController.tsx
  src/pages/profile/edit/ProfileEditPage.tsx
Labels: Priority: Critical, Type: Bug

#162 fix: 상세 조건 하이라이트 버그 수정 - 배포 사이트에 적용
  src/components/recruit/recruitBoard/detailedFilter/DetailedInput.tsx
  src/pages/recruit/recruitPage/RecruitPage.tsx
Labels: Priority: Critical, Type: Bug

#164 fix: 프로필 편집 페이지, 포트폴리오 작성/편집 페이지, 회원가입 완료 페이지 2차 QA 피드백 적용
  src/components/index.ts
  src/components/modal/Modal.styled.ts
  src/components/modal/Modal.tsx
  src/components/radio/Radio.tsx
  src/constant/validation.ts
  src/pages/account/complete/CompleteSignUpPage.tsx
  src/pages/portfolio/edit/PortfolioEditPage.tsx
  src/pages/profile/edit/ProfileEditPage.tsx
Labels: Priority: Critical, Status: Review Needed, Type: Bug

#167 feat: #140 신청자 관리 페이지 접근 권한 없을 때, 리다이렉션
  src/service/axiosInstance.ts
  src/service/recruit/applicant.ts
Labels: Priority: High, Status: Review Needed, Type: Improvement

#168 feat: 접근권한 없는 페이지 접근 시, 로그인 페이지로 리다이렉션 - 배포 사이트 적용
  src/service/axiosInstance.ts
  src/service/recruit/applicant.ts
Labels: Priority: Critical, Type: Improvement

#169 fix: 불필요한 API 호출 횟수 감소
  src/components/dropdown/Dropdown.tsx
Labels: Priority: Critical, Type: Bug

#174 fix: 텍스트 에디터 string 타입으로 인한 에러 수정 및 들여쓰기 반영
  src/components/recruit/create/detailedInformation/DetailedInformation.tsx
  src/components/recruit/recruitDetail/recruitDescription/RecruitDescription.styled.ts
  src/pages/recruit/recruitDetailPage/RecruitDetailPage.tsx
Labels: Priority: Critical, Type: Bug

#177 fix: 디자인 미적용사항 반영 및 일부 버그 수정
  src/assets/SearchIcon.svg
  src/atom.tsx
  src/components/dropdown/Dropdown.tsx
  src/components/index.ts
  src/components/inputDropdown/inputRole/InputRoleForm.styled.ts
  src/components/inputDropdown/inputRole/InputRoleForm.tsx
  src/components/recruit/create/RecruitTags.tsx
  src/components/recruit/create/basicInformation/containers/ContainerCourse.tsx
  src/components/recruit/create/recruitRoles/RecruitRolesForm.tsx
  src/components/recruit/recruitBoard/detailedFilter/DetailedInput.tsx
  src/components/recruit/recruitDetail/footer/WriterFooter.tsx
  src/components/recruit/recruitDetail/linktoList/LinkToList.styled.ts
  src/components/recruit/recruitDetail/modal/warnRoleDelete/WarnRoleDelete.styled.ts
  src/components/recruit/recruitDetail/modal/warnRoleDelete/WarnRoleDelete.tsx
  src/components/recruit/recruitDetail/recruitTag/RecruitTag.tsx
  src/components/tag/MeeteamTag.tsx
  src/globalStyle.css
  src/hooks/useValid.ts
  src/pages/create/recruitCreatePage/RecruitCreatePage.styled.ts
  src/pages/create/recruitCreatePage/RecruitCreatePage.tsx
  src/pages/recruit/recruitDetailPage/RecruitDetailPage.styled.ts
  src/pages/recruit/recruitDetailPage/RecruitDetailPage.tsx
  src/pages/recruit/recruitManagePage/RecruitMyPostings.tsx
  src/pages/recruit/recruitManagePage/RecruitPostingApply.tsx
  src/pages/recruit/recruitManagePage/RecruitPostingBookmark.tsx
  src/pages/recruit/recruitPage/RecruitPage.styled.ts
  src/pages/recruit/recruitPage/RecruitPage.tsx
  src/types/index.ts
  src/types/recruit/response.ts
Labels: Priority: Critical, Status: Review Needed, Type: Bug, Type: Improvement, Type: Style

#179 fix: 텍스트 에디터 버그 검토 및 개선
  src/components/header/Header.tsx
  src/components/meeteam/card/RecruitCard.tsx
  src/components/recruit/create/ControlButtons.tsx
  src/components/recruit/create/detailedInformation/DetailedInformation.styled.ts
  src/components/recruit/create/detailedInformation/DetailedInformation.tsx
  src/components/recruit/recruitDetail/recruitDescription/RecruitDescription.styled.ts
  src/constant/textEditor.ts
  src/pages/create/recruitCreatePage/RecruitCreatePage.tsx
  src/pages/recruit/recruitDetailPage/data.ts
  src/utils/editorModule.ts
  src/utils/resetFormData.ts
Labels: Priority: Critical, Status: Review Needed, Type: Bug, Type: Improvement

#184 feat: 로컬스토리지 암호화 및 일부 버그 수정, 기능 추가
  index.html
  src/assets/LogoFooter.svg
  src/assets/index.ts
  src/atom.tsx
  src/components/comment/comment/Comment.styled.ts
  src/components/comment/comment/Comment.tsx
  src/components/comment/comment/ReplyComment.styled.ts
  src/components/comment/comment/ReplyComment.tsx
  src/components/comment/commentInput/CommentInput.styled.ts
  src/components/comment/replyInput/ReplyInput.styled.ts
  src/components/comment/replyInput/ReplyInput.tsx
  src/components/footer/Footer.styled.ts
  src/components/footer/Footer.tsx
  src/components/header/Header.styled.ts
  src/components/header/Header.tsx
  src/components/index.ts
  src/components/meeteam/tag/Tag.styled.ts
  src/components/pagination/Pagination.tsx
  src/components/recruit/applicants/toast/Toast.styled.ts
  src/components/recruit/recruitDetail/modal/ApplyModal.styled.ts
  src/components/recruit/recruitDetail/recruitDescription/RecruitDescription.styled.ts
  src/components/recruit/recruitDetail/recruitRoles/RecruitRoles.styled.ts
  src/components/recruit/role/RoleCard.styled.ts
  src/components/recruit/role/RoleCard.tsx
  src/env.d.ts
  src/hooks/useAuth.ts
  src/hooks/useLogin.ts
  src/pages/account/schoolCertification/SchoolCertificationPage.tsx
  src/pages/account/signIn/SignInPage.tsx
  src/pages/create/recruitCreatePage/RecruitCreatePage.styled.ts
  src/pages/recruit/applierManagePage/ApplierManagePage.styled.ts
  src/pages/recruit/recruitDetailPage/RecruitDetailPage.styled.ts
  src/pages/recruit/recruitManagePage/RecruitManagePage.styled.ts
  src/pages/recruit/recruitPage/RecruitPage.styled.ts
  src/pages/recruit/recruitPage/RecruitPage.tsx
  src/service/axiosInstance.ts
  src/service/endPoint.ts
  src/types/user.ts
Labels: Priority: Critical, Type: Bug, Type: Improvement

#187 deploy: 로컬스토리지 암호화 및 일부 버그 수정, 기능 추가
  index.html
  src/assets/LogoFooter.svg
  src/assets/index.ts
  src/atom.tsx
  src/components/comment/comment/Comment.styled.ts
  src/components/comment/comment/Comment.tsx
  src/components/comment/comment/ReplyComment.styled.ts
  src/components/comment/comment/ReplyComment.tsx
  src/components/comment/commentInput/CommentInput.styled.ts
  src/components/comment/replyInput/ReplyInput.styled.ts
  src/components/comment/replyInput/ReplyInput.tsx
  src/components/footer/Footer.styled.ts
  src/components/footer/Footer.tsx
  src/components/header/Header.styled.ts
  src/components/header/Header.tsx
  src/components/index.ts
  src/components/meeteam/tag/Tag.styled.ts
  src/components/pagination/Pagination.tsx
  src/components/recruit/applicants/toast/Toast.styled.ts
  src/components/recruit/recruitDetail/modal/ApplyModal.styled.ts
  src/components/recruit/recruitDetail/recruitDescription/RecruitDescription.styled.ts
  src/components/recruit/recruitDetail/recruitRoles/RecruitRoles.styled.ts
  src/components/recruit/role/RoleCard.styled.ts
  src/components/recruit/role/RoleCard.tsx
  src/env.d.ts
  src/hooks/useAuth.ts
  src/hooks/useLogin.ts
  src/pages/account/schoolCertification/SchoolCertificationPage.tsx
  src/pages/account/signIn/SignInPage.tsx
  src/pages/create/recruitCreatePage/RecruitCreatePage.styled.ts
  src/pages/recruit/applierManagePage/ApplierManagePage.styled.ts
  src/pages/recruit/recruitDetailPage/RecruitDetailPage.styled.ts
  src/pages/recruit/recruitManagePage/RecruitManagePage.styled.ts
  src/pages/recruit/recruitPage/RecruitPage.styled.ts
  src/pages/recruit/recruitPage/RecruitPage.tsx
  src/service/axiosInstance.ts
  src/service/endPoint.ts
  src/types/user.ts
Labels: Priority: Critical, Type: Bug, Type: Feature, Type: Improvement, Type: Style

#190 fix: <긴급> 로그인 관련 버그 수정
  src/atom.tsx
  src/components/comment/comment/Comment.tsx
  src/components/comment/comment/ReplyComment.tsx
  src/components/comment/replyInput/ReplyInput.tsx
  src/components/dropdown/Dropdown.tsx
  src/components/header/Header.tsx
  src/components/meeteam/card/RecruitCard.tsx
  src/components/recruit/create/recruitRoles/RecruitRolesForm.tsx
  src/components/recruit/recruitDetail/footer/ApplierFooter.tsx
  src/components/recruit/recruitDetail/titleInfo/TitleInfo.tsx
  src/hooks/useLogin.ts
  src/pages/create/recruitCreatePage/RecruitCreatePage.tsx
  src/pages/recruit/recruitDetailPage/RecruitDetailPage.tsx
  src/pages/recruit/recruitPage/RecruitPage.tsx
  src/service/recruit/board.ts
  src/service/recruit/detail.ts
Labels: Priority: Critical, Type: Bug

#193 deploy: 일부 버그 수정 및 개선 - 배포 사이트에 적용
  src/components/recruit/recruitDetail/modal/ApplyModal.styled.ts
  src/components/recruit/recruitDetail/modal/postingDelete/PostingDelete.tsx
  src/components/recruit/recruitDetail/recruitDescription/RecruitDescription.styled.ts
  src/components/recruit/recruitDetail/recruitDescription/RecruitDescription.tsx
  src/constant/textEditor.ts
  src/globalStyle.css
  src/pages/recruit/recruitDetailPage/RecruitDetailPage.tsx
Labels: Priority: Critical, Type: Bug, Type: Improvement

#198 fix: 5차 QA 피드백 적용
  src/components/muiDatepicker/MuiDatepickerController.tsx
  src/pages/portfolio/details/PortfolioDetails.styled.ts
  src/pages/portfolio/details/PortfolioDetailsPage.tsx
  src/pages/portfolio/edit/PortfolioEditPage.tsx
  src/utils/addClassToEmptyPTags.ts
  src/utils/index.ts
Labels: Priority: Critical, Status: Review Needed, Type: Bug

#206 fix: 6차 QA 피드백 적용
  src/components/index.ts
  src/components/modal/Modal.styled.ts
  src/components/modal/Modal.tsx
  src/components/muiDatepicker/MuiDatepicker.tsx
  src/components/portfolio/image/upload/PortfolioImageUpload.tsx
  src/components/portfolio/modal/PortfolioModal.styled.ts
  src/components/portfolio/modal/PortfolioModal.tsx
  src/constant/validation.ts
  src/hooks/useProfile.ts
  src/pages/account/signIn/SignInPage.tsx
  src/pages/portfolio/edit/PortfolioEditPage.tsx
  src/pages/profile/edit/ProfileEditPage.tsx
  src/service/user/Profile.ts
Labels: Priority: Critical, Status: Review Needed, Type: Bug
