Repository MeeTeamIdle/MeeTeam_FrontEnd, pull requests merged in 2024-10, with the labels that each got.

#250 refactor: #248. 모달 관련 커스텀훅 적용 및 이미지 webp 적용
  src/assets/NaverIcon.png
  src/assets/NaverIcon.webp
  src/assets/NotFoundIcon.png
  src/assets/NotFoundIcon.webp
  src/assets/index.ts
  src/assets/meeteam_banner_icon.png
  src/assets/meeteam_banner_icon.webp
  src/components/dropdown/Dropdown.tsx
  src/components/header/Header.tsx
  src/components/inputDropdown/inputRole/InputRoleForm.styled.ts
  src/components/inputDropdown/inputRole/InputRoleForm.tsx
  src/components/recruit/create/basicInformation/containers/ContainerCourse.tsx
  src/components/tag/MeeteamTag.tsx
  src/hooks/index.ts
  src/hooks/useFixModalBackground.ts
  src/hooks/useFocusOnTop.ts
  src/hooks/useOutsideClick.ts
  src/hooks/useScrollToTop.ts
  src/pages/recruit/recruitPage/RecruitPage.tsx
Labels: Priority: Medium, Status: Review Needed, Type: Refactor

#252 deploy: #248. 모달 관련 커스텀훅 적용 및 이미지 webp 적용
  src/assets/NaverIcon.png
  src/assets/NaverIcon.webp
  src/assets/NotFoundIcon.png
  src/assets/NotFoundIcon.webp
  src/assets/index.ts
  src/assets/meeteam_banner_icon.png
  src/assets/meeteam_banner_icon.webp
  src/components/dropdown/Dropdown.tsx
  src/components/header/Header.tsx
  src/components/inputDropdown/inputRole/InputRoleForm.styled.ts
  src/components/inputDropdown/inputRole/InputRoleForm.tsx
  src/components/recruit/create/basicInformation/containers/ContainerCourse.tsx
  src/components/tag/MeeteamTag.tsx
  src/hooks/index.ts
  src/hooks/useFixModalBackground.ts
  src/hooks/useFocusOnTop.ts
  src/hooks/useOutsideClick.ts
  src/hooks/useScrollToTop.ts
  src/pages/recruit/recruitPage/RecruitPage.tsx
Labels: Priority: Medium, Type: Improvement, Type: Refactor

#253 refactor: LCP 시간 감소하도록 개선
  index.html
  public/logo_large.webp
  public/logo_medium.webp
  public/logo_small copy.webp
  public/logo_small.webp
  public/logo_typo_large.webp
  public/logo_typo_medium.webp
  public/logo_typo_small.webp
  public/meeteam_banner_icon_large.webp
  public/meeteam_banner_icon_medium.webp
  public/meeteam_banner_icon_small.webp
  sitemap.xml
  src/assets/index.ts
  src/assets/meeteam_banner_icon.webp
  src/components/comment/comment/ReplyComment.tsx
  src/components/comment/replyInput/ReplyInput.tsx
  src/components/dropdown/Dropdown.tsx
  src/components/dropdown/dropdownDetail/DropdownDetail.tsx
  src/components/footer/Footer.styled.ts
  src/components/footer/Footer.tsx
  src/components/header/Header.styled.ts
  src/components/header/Header.tsx
  src/components/inputDropdown/inputRole/InputRole.tsx
  src/components/inputDropdown/inputRole/InputRoleForm.tsx
  src/components/meeteam/card/RecruitCard.tsx
  src/components/recruit/applicants/ApplicantCard.tsx
  src/components/recruit/applicants/toast/Toast.tsx
  src/components/recruit/create/recruitRoles/RecruitRolesForm.tsx
  src/components/recruit/recruitBoard/banner/MainBanner.styled.ts
  src/components/recruit/recruitBoard/banner/MainBanner.tsx
  src/components/recruit/recruitBoard/clear/ClearConditions.tsx
  src/components/recruit/recruitBoard/detailedFilter/DetailedInput.tsx
  src/components/recruit/recruitBoard/fieldPopup/FieldPopup.tsx
  src/components/recruit/recruitBoard/floatingButton/FloatingButton.tsx
  src/components/recruit/recruitBoard/searchBar/SearchBar.tsx
  src/components/recruit/recruitDetail/footer/ApplierFooter.tsx
  src/components/recruit/recruitDetail/footer/WriterFooter.tsx
  src/components/recruit/recruitDetail/modal/ApplyModal.tsx
  src/components/tag/MeeteamTag.tsx
  src/main.tsx
  src/pages/notFound/NotFound.tsx
  src/pages/recruit/applierManagePage/ApplierManagePage.tsx
  src/pages/recruit/recruitPage/RecruitPage.tsx
  src/service/recruit/board.ts
Labels: Priority: High, Status: Review Needed, Type: Improvement, Type: Refactor

#256 deploy: LCP 최적화 반영
  index.html
  public/logo_large.webp
  public/logo_medium.webp
  public/logo_small copy.webp
  public/logo_small.webp
  public/logo_typo_large.webp
  public/logo_typo_medium.webp
  public/logo_typo_small.webp
  public/meeteam_banner_icon_large.webp
  public/meeteam_banner_icon_medium.webp
  public/meeteam_banner_icon_small.webp
  sitemap.xml
  src/assets/index.ts
  src/assets/meeteam_banner_icon.webp
  src/components/comment/comment/ReplyComment.tsx
  src/components/comment/replyInput/ReplyInput.tsx
  src/components/dropdown/Dropdown.tsx
  src/components/dropdown/dropdownDetail/DropdownDetail.tsx
  src/components/footer/Footer.styled.ts
  src/components/footer/Footer.tsx
  src/components/header/Header.styled.ts
  src/components/header/Header.tsx
  src/components/inputDropdown/inputRole/InputRole.tsx
  src/components/inputDropdown/inputRole/InputRoleForm.tsx
  src/components/meeteam/card/RecruitCard.tsx
  src/components/recruit/applicants/ApplicantCard.tsx
  src/components/recruit/applicants/toast/Toast.tsx
  src/components/recruit/create/recruitRoles/RecruitRolesForm.tsx
  src/components/recruit/recruitBoard/banner/MainBanner.styled.ts
  src/components/recruit/recruitBoard/banner/MainBanner.tsx
  src/components/recruit/recruitBoard/clear/ClearConditions.tsx
  src/components/recruit/recruitBoard/detailedFilter/DetailedInput.tsx
  src/components/recruit/recruitBoard/fieldPopup/FieldPopup.tsx
  src/components/recruit/recruitBoard/floatingButton/FloatingButton.tsx
  src/components/recruit/recruitBoard/searchBar/SearchBar.tsx
  src/components/recruit/recruitDetail/footer/ApplierFooter.tsx
  src/components/recruit/recruitDetail/footer/WriterFooter.tsx
  src/components/recruit/recruitDetail/modal/ApplyModal.tsx
  src/components/tag/MeeteamTag.tsx
  src/main.tsx
  src/pages/notFound/NotFound.tsx
  src/pages/recruit/applierManagePage/ApplierManagePage.tsx
  src/pages/recruit/recruitPage/RecruitPage.tsx
  src/service/recruit/board.ts
Labels: Priority: Medium, Type: Improvement, Type: Refactor

#260 fix: 프로필 이미지 편집 이후, 편집 버튼 누르면 프로필 상세페이지로 리다이렉트 되는 이슈 해결
  src/pages/profile/edit/ProfileEditPage.tsx
Labels: Priority: Critical, Status: Available, Type: Bug, D-1

#263 chore: 일부 버그 수정 및 드롭다운 수정 / 웹 사이트 분석을 위한 코드 추가
  index.html
  src/components/footer/Footer.tsx
  src/components/header/Header.tsx
  src/components/inputDropdown/inputRole/InputRoleForm.styled.ts
  src/components/inputDropdown/inputRole/InputRoleForm.tsx
  src/components/recruit/create/basicInformation/containers/ContainerCourse.tsx
  src/components/tag/MeeteamTag.tsx
Labels: Priority: High, Status: Review Needed, Type: Bug, D-0

#265 deploy: 일부 버그 수정 및 드롭다운 개선 / 웹 사이트 분석을 위한 코드 추가
  index.html
  src/components/footer/Footer.tsx
  src/components/header/Header.tsx
  src/components/inputDropdown/inputRole/InputRoleForm.styled.ts
  src/components/inputDropdown/inputRole/InputRoleForm.tsx
  src/components/recruit/create/basicInformation/containers/ContainerCourse.tsx
  src/components/tag/MeeteamTag.tsx
Labels: Priority: Critical, Status: Available, Type: Bug, Type: Improvement
